export interface department {
  id: number;
  title: string;
  municipalities: municipality[];
}

export interface municipality {
  id: number;
  title: string;
}

export const guatemala: department[] = [
  {
    id: 1,
    title: "Alta Verapaz",
    municipalities: [
      { id: 1, title: "Chahal" },
      { id: 2, title: "Chisec" },
      { id: 3, title: "Cobán" },
      { id: 4, title: "Fray Bartolomé de las Casas" },
      { id: 5, title: "Lanquín" },
      { id: 6, title: "Panzós" },
      { id: 7, title: "Raxruha" },
      { id: 8, title: "San Cristóbal Verapaz" },
      { id: 9, title: "San Juan Chamelco" },
      { id: 10, title: "San Pedro Carchá" },
      { id: 11, title: "Santa Cruz Verapaz" },
      { id: 12, title: "Senahú" },
      { id: 13, title: "Tactic" },
      { id: 14, title: "Tamahú" },
      { id: 15, title: "Tucurú" },
      { id: 16, title: "Santa María Cahabón" },
      { id: 17, title: "Santa Catarina La Tinta" },
    ],
  },
  {
    id: 2,
    title: "Baja Verapaz",
    municipalities: [
      { id: 18, title: "Cubulco" },
      { id: 19, title: "Granados" },
      { id: 20, title: "Purulhá" },
      { id: 21, title: "Rabinal" },
      { id: 22, title: "Salamá" },
      { id: 23, title: "San Jerónimo" },
      { id: 24, title: "San Miguel Chicaj" },
      { id: 25, title: "Santa Cruz El Chol" },
    ],
  },
  {
    id: 3,
    title: "Chimaltenango",
    municipalities: [
      { id: 26, title: "Acatenango" },
      { id: 27, title: "Chimaltenango" },
      { id: 28, title: "El Tejar" },
      { id: 29, title: "Parramos" },
      { id: 30, title: "Patzicía" },
      { id: 31, title: "Patzún" },
      { id: 32, title: "Pochuta" },
      { id: 33, title: "San Andrés Itzapa" },
      { id: 34, title: "San José Poaquil" },
      { id: 35, title: "San Juan Comalapa" },
      { id: 36, title: "San Martín Jilotepeque" },
      { id: 37, title: "Santa Apolonia" },
      { id: 38, title: "Santa Cruz Balanyá" },
      { id: 39, title: "Tecpán Guatemala" },
      { id: 40, title: "Yepocapa" },
      { id: 41, title: "Zaragoza" },
    ],
  },
  {
    id: 4,
    title: "Chiquimula",
    municipalities: [
      { title: "Camotán", id: 42 },
      { title: "Chiquimula", id: 43 },
      { title: "Concepción Las Minas", id: 44 },
      { title: "Esquipulas", id: 45 },
      { title: "Ipala", id: 46 },
      { title: "Jocotán", id: 47 },
      { title: "Olopa", id: 48 },
      { title: "Quezaltepeque", id: 49 },
      { title: "San Jacinto", id: 50 },
      { title: "San José La Arada", id: 51 },
      { title: "San Juan Ermita", id: 52 },
    ],
  },
  {
    id: 5,
    title: "El Progreso",
    municipalities: [
      { title: "El Jícaro", id: 53 },
      { title: "Guastatoya", id: 54 },
      { title: "Morazán", id: 55 },
      { title: "San Agustín Acasaguastlán", id: 56 },
      { title: "San Antonio La Paz", id: 57 },
      { title: "San Cristóbal Acasaguastlán", id: 58 },
      { title: "Sanarate", id: 59 },
    ],
  },
  {
    id: 6,
    title: "Escuintla",
    municipalities: [
      { title: "Escuintla", id: 60 },
      { title: "Guanagazapa", id: 61 },
      { title: "Iztapa", id: 62 },
      { title: "La Democracia", id: 63 },
      { title: "La Gomera", id: 64 },
      { title: "Masagua", id: 65 },
      { title: "Nueva Concepción", id: 66 },
      { title: "Palín", id: 67 },
      { title: "San José", id: 68 },
      { title: "San Vicente Pacaya", id: 69 },
      { title: "Santa Lucía Cotzumalguapa", id: 70 },
      { title: "Siquinalá", id: 71 },
      { title: "Tiquisate", id: 72 },
    ],
  },
  {
    id: 7,
    title: "Guatemala",
    municipalities: [
      { title: "Amatitlán", id: 73 },
      { title: "Chinautla", id: 74 },
      { title: "Chuarrancho", id: 75 },
      { title: "Fraijanes", id: 76 },
      { title: "Guatemala City", id: 77 },
      { title: "Mixco", id: 78 },
      { title: "Palencia", id: 79 },
      { title: "Petapa", id: 80 },
      { title: "San José del Golfo", id: 81 },
      { title: "San José Pinula", id: 82 },
      { title: "San Juan Sacatepéquez", id: 83 },
      { title: "San Pedro Ayampuc", id: 84 },
      { title: "San Pedro Sacatepéquez", id: 85 },
      { title: "San Raymundo", id: 86 },
      { title: "Santa Catarina Pinula", id: 87 },
      { title: "Villa Canales", id: 88 },
    ],
  },
  {
    id: 8,
    title: "Huehuetenango",
    municipalities: [
      { title: "Aguacatán", id: 89 },
      { title: "Chiantla", id: 90 },
      { title: "Colotenango", id: 91 },
      { title: "Concepción Huista", id: 92 },
      { title: "Cuilco", id: 93 },
      { title: "Huehuetenango", id: 94 },
      { title: "Ixtahuacán", id: 95 },
      { title: "Jacaltenango", id: 96 },
      { title: "La Democracia", id: 97 },
      { title: "La Libertad", id: 98 },
      { title: "Malacatancito", id: 99 },
      { title: "Nentón", id: 100 },
      { title: "San Antonio Huista", id: 101 },
      { title: "San Gaspar Ixchil", id: 102 },
      { title: "San Juan Atitán", id: 103 },
      { title: "San Juan Ixcoy", id: 104 },
      { title: "San Mateo Ixtatán", id: 105 },
      { title: "San Miguel Acatán", id: 106 },
      { title: "San Pedro Necta", id: 107 },
      { title: "San Rafael La Independencia", id: 108 },
      { title: "San Rafael Petzal", id: 109 },
      { title: "San Sebastián Coatán", id: 110 },
      { title: "San Sebastián Huehuetenango", id: 111 },
      { title: "Santa Ana Huista", id: 112 },
      { title: "Santa Bárbara", id: 113 },
      { title: "Santa Cruz Barillas", id: 114 },
      { title: "Santa Eulalia", id: 115 },
      { title: "Santiago Chimaltenango", id: 116 },
      { title: "Soloma", id: 117 },
      { title: "Tectitán", id: 118 },
      { title: "Todos Santos Cuchumatan", id: 119 },
    ],
  },
  {
    id: 9,
    title: "Izabal",
    municipalities: [
      { title: "El Estor", id: 120 },
      { title: "Livingston", id: 121 },
      { title: "Los Amates", id: 122 },
      { title: "Morales", id: 123 },
      { title: "Puerto Barrios", id: 124 },
    ],
  },
  {
    id: 10,
    title: "Jalapa",
    municipalities: [
      { title: "Jalapa", id: 125 },
      { title: "Mataquescuintla", id: 126 },
      { title: "Monjas", id: 127 },
      { title: "San Carlos Alzatate", id: 128 },
      { title: "San Luis Jilotepeque", id: 129 },
      { title: "San Manuel Chaparrón", id: 130 },
      { title: "San Pedro Pinula", id: 131 },
    ],
  },
  {
    id: 11,
    title: "Jutiapa",
    municipalities: [
      { title: "Agua Blanca", id: 132 },
      { title: "Asunción Mita", id: 133 },
      { title: "Atescatempa", id: 134 },
      { title: "Comapa", id: 135 },
      { title: "Conguaco", id: 136 },
      { title: "El Adelanto", id: 137 },
      { title: "El Progreso", id: 138 },
      { title: "Jalpatagua", id: 139 },
      { title: "Jerez", id: 140 },
      { title: "Jutiapa", id: 141 },
      { title: "Moyuta", id: 142 },
      { title: "Pasaco", id: 143 },
      { title: "Quezada", id: 144 },
      { title: "San José Acatempa", id: 145 },
      { title: "Santa Catarina Mita", id: 146 },
      { title: "Yupiltepeque", id: 147 },
      { title: "Zapotitlán", id: 148 },
    ],
  },
  {
    id: 12,
    title: "Petén",
    municipalities: [
      { title: "Dolores", id: 149 },
      { title: "Flores", id: 150 },
      { title: "La Libertad", id: 151 },
      { title: "Melchor de Mencos", id: 152 },
      { title: "Poptún", id: 153 },
      { title: "San Andrés", id: 154 },
      { title: "San Benito", id: 155 },
      { title: "San Francisco", id: 156 },
      { title: "San José", id: 157 },
      { title: "San Luis", id: 158 },
      { title: "Santa Ana", id: 159 },
      { title: "Sayaxché", id: 160 },
      { title: "Las Cruces", id: 161 },
    ],
  },
  {
    id: 13,
    title: "Quetzaltenango",
    municipalities: [
      { title: "Almolonga", id: 162 },
      { title: "Cabricán", id: 163 },
      { title: "Cajolá", id: 164 },
      { title: "Cantel", id: 165 },
      { title: "Coatepeque", id: 166 },
      { title: "Colomba", id: 167 },
      { title: "Concepción Chiquirichapa", id: 168 },
      { title: "El Palmar", id: 169 },
      { title: "Flores Costa Cuca", id: 170 },
      { title: "Génova", id: 171 },
      { title: "Huitán", id: 172 },
      { title: "La Esperanza", id: 173 },
      { title: "Olintepeque", id: 174 },
      { title: "Ostuncalco", id: 175 },
      { title: "Palestina de Los Altos", id: 176 },
      { title: "Quetzaltenango", id: 177 },
      { title: "Salcajá", id: 178 },
      { title: "San Carlos Sija", id: 179 },
      { title: "San Francisco La Unión", id: 180 },
      { title: "San Martín Sacatepéquez", id: 181 },
      { title: "San Mateo", id: 182 },
      { title: "San Miguel Sigüilá", id: 183 },
      { title: "Sibilia", id: 184 },
      { title: "Zunil", id: 185 },
    ],
  },
  {
    id: 14,
    title: "Quiché",
    municipalities: [
      { title: "Canillá", id: 186 },
      { title: "Chajul", id: 187 },
      { title: "Chicamán", id: 188 },
      { title: "Chiché", id: 189 },
      { title: "Chichicastenango", id: 190 },
      { title: "Chinique", id: 191 },
      { title: "Cunén", id: 192 },
      { title: "Ixcán", id: 193 },
      { title: "Joyabaj", id: 194 },
      { title: "Nebaj", id: 195 },
      { title: "Pachalum", id: 196 },
      { title: "Patzité", id: 197 },
      { title: "Sacapulas", id: 198 },
      { title: "San Andrés Sajcabajá", id: 199 },
      { title: "San Antonio Ilotenango", id: 200 },
      { title: "San Bartolomé Jocotenango", id: 201 },
      { title: "San Juan Cotzal", id: 202 },
      { title: "San Pedro Jocopilas", id: 203 },
      { title: "Santa Cruz del Quiché", id: 204 },
      { title: "Uspantán", id: 205 },
      { title: "Zacualpa", id: 206 },
    ],
  },
  {
    id: 15,
    title: "Retalhuleu",
    municipalities: [
      { title: "Champerico", id: 207 },
      { title: "El Asintal", id: 208 },
      { title: "Nuevo San Carlos", id: 209 },
      { title: "Retalhuleu", id: 210 },
      { title: "San Andrés Villa Seca", id: 211 },
      { title: "San Felipe", id: 212 },
      { title: "San Martín Zapotitlán", id: 213 },
      { title: "San Sebastián", id: 214 },
      { title: "Santa Cruz Muluá", id: 215 },
    ],
  },
  {
    id: 16,
    title: "Sacatepéquez",
    municipalities: [
      { title: "Alotenango", id: 216 },
      { title: "Antigua", id: 217 },
      { title: "Ciudad Vieja", id: 218 },
      { title: "Jocotenango", id: 219 },
      { title: "Magdalena Milpas Altas", id: 220 },
      { title: "Pastores", id: 221 },
      { title: "San Antonio Aguas Calientes", id: 222 },
      { title: "San Bartolomé Milpas Altas", id: 223 },
      { title: "San Lucas Sacatepéquez", id: 224 },
      { title: "San Miguel Dueñas", id: 225 },
      { title: "Santa Catarina Barahona", id: 226 },
      { title: "Santa Lucía Milpas Altas", id: 227 },
      { title: "Santa María de Jesús", id: 228 },
      { title: "Santiago Sacatepéquez", id: 229 },
      { title: "Santo Domingo Xenacoj", id: 230 },
      { title: "Sumpango", id: 231 },
    ],
  },
  {
    id: 17,
    title: "San Marcos",
    municipalities: [
      { title: "Ayutla", id: 232 },
      { title: "Catarina", id: 233 },
      { title: "Comitancillo", id: 234 },
      { title: "Concepción Tutuapa", id: 235 },
      { title: "El Quetzal", id: 236 },
      { title: "El Rodeo", id: 237 },
      { title: "El Tumbador", id: 238 },
      { title: "Esquipulas Palo Gordo", id: 239 },
      { title: "Ixchiguan", id: 240 },
      { title: "La Reforma", id: 241 },
      { title: "Malacatán", id: 242 },
      { title: "Nuevo Progreso", id: 243 },
      { title: "Ocos", id: 244 },
      { title: "Pajapita", id: 245 },
      { title: "Río Blanco", id: 246 },
      { title: "San Antonio Sacatepéquez", id: 247 },
      { title: "San Cristóbal Cucho", id: 248 },
      { title: "San José Ojetenam", id: 249 },
      { title: "San Lorenzo", id: 250 },
      { title: "San Marcos", id: 251 },
      { title: "San Miguel Ixtahuacán", id: 252 },
      { title: "San Pablo", id: 253 },
      { title: "San Pedro Sacatepéquez", id: 254 },
      { title: "San Rafael Pie de La Cuesta", id: 255 },
      { title: "San Sibinal", id: 256 },
      { title: "Sipacapa", id: 257 },
      { title: "Tacaná", id: 258 },
      { title: "Tajumulco", id: 259 },
      { title: "Tejutla", id: 260 },
    ],
  },
  {
    id: 18,
    title: "Santa Rosa",
    municipalities: [
      { title: "Barberena", id: 261 },
      { title: "Casillas", id: 262 },
      { title: "Chiquimulilla", id: 263 },
      { title: "Cuilapa", id: 264 },
      { title: "Guazacapán", id: 265 },
      { title: "Nueva Santa Rosa", id: 266 },
      { title: "Oratorio", id: 267 },
      { title: "Pueblo Nuevo Viñas", id: 268 },
      { title: "San Juan Tecuaco", id: 269 },
      { title: "San Rafael Las Flores", id: 270 },
      { title: "Santa Cruz Naranjo", id: 271 },
      { title: "Santa María Ixhuatán", id: 272 },
      { title: "Santa Rosa de Lima", id: 273 },
      { title: "Taxisco", id: 274 },
    ],
  },
  {
    id: 19,
    title: "Sololá",
    municipalities: [
      { title: "Concepción", id: 275 },
      { title: "Nahualá", id: 276 },
      { title: "Panajachel", id: 277 },
      { title: "San Andrés Semetabaj", id: 278 },
      { title: "San Antonio Palopó", id: 279 },
      { title: "San José Chacaya", id: 280 },
      { title: "San Juan La Laguna", id: 281 },
      { title: "San Lucas Tolimán", id: 282 },
      { title: "San Marcos La Laguna", id: 283 },
      { title: "San Pablo La Laguna", id: 284 },
      { title: "San Pedro La Laguna", id: 285 },
      { title: "Santa Catarina Ixtahuacan", id: 286 },
      { title: "Santa Catarina Palopó", id: 287 },
      { title: "Santa Clara La Laguna", id: 288 },
      { title: "Santa Cruz La Laguna", id: 289 },
      { title: "Santa Lucía Utatlán", id: 290 },
      { title: "Santa María Visitación", id: 291 },
      { title: "Santiago Atitlán", id: 292 },
      { title: "Sololá", id: 293 },
    ],
  },
  {
    id: 20,
    title: "Suchitepéquez",
    municipalities: [
      { title: "Chicacao", id: 294 },
      { title: "Cuyotenango", id: 295 },
      { title: "Mazatenango", id: 296 },
      { title: "Patulul", id: 297 },
      { title: "Pueblo Nuevo", id: 298 },
      { title: "Río Bravo", id: 299 },
      { title: "Samayac", id: 300 },
      { title: "San Antonio Suchitepéquez", id: 301 },
      { title: "San Bernardino", id: 302 },
      { title: "San Francisco Zapotitlán", id: 303 },
      { title: "San Gabriel", id: 304 },
      { title: "San José El Idolo", id: 305 },
      { title: "San Juan Bautista", id: 306 },
      { title: "San Lorenzo", id: 307 },
      { title: "San Miguel Panán", id: 308 },
      { title: "San Pablo Jocopilas", id: 309 },
      { title: "Santa Bárbara", id: 310 },
      { title: "Santo Domingo Suchitepequez", id: 311 },
      { title: "Santo Tomas La Unión", id: 312 },
      { title: "Zunilito", id: 313 },
    ],
  },
  {
    id: 21,
    title: "Totonicapán",
    municipalities: [
      { title: "Momostenango", id: 314 },
      { title: "San Andrés Xecul", id: 315 },
      { title: "San Bartolo", id: 316 },
      { title: "San Cristóbal Totonicapán", id: 317 },
      { title: "San Francisco El Alto", id: 318 },
      { title: "Santa Lucía La Reforma", id: 319 },
      { title: "Santa María Chiquimula", id: 320 },
      { title: "Totonicapán", id: 321 },
    ],
  },
  {
    id: 22,
    title: "Zacapa",
    municipalities: [
      { title: "Cabañas", id: 322 },
      { title: "Estanzuela", id: 323 },
      { title: "Gualán", id: 324 },
      { title: "Huité", id: 325 },
      { title: "La Unión", id: 326 },
      { title: "Río Hondo", id: 327 },
      { title: "San Diego", id: 328 },
      { title: "Teculután", id: 329 },
      { title: "Usumatlán", id: 330 },
      { title: "Zacapa", id: 331 },
    ],
  },
];
